export const labels = {
  labels: 'labels',
  SignUp: 'Sign Up',
  Login: 'Login',
  FullName: 'Full Name',
  staric: '*',
  LastName: 'Last Name',
  PhoneNumber: 'Phone Number',
  Password: 'Password',
  Email: 'Email',
  ConfirmPassword: 'Confirm Password',
  alreadyHaveAccount: 'Already Have An Account?',
  haveAccountSignUp: "Don't Have Account? ",
  forgetPassword: 'Forget Password?',
  passwordRecovery: 'Password Recovery',
  backToLogin: 'Back To Login',
  continue: 'Continue',
  verification: 'Verification',
  verificationCode: 'Verification Code*',
  resend: 'Resend',
  didNt: "Didn't Receive?  ",
};
