export const labels = {
  labels: 'labels',
  SignUp: 'Sign Up',
  Login: 'Login',
  FullName: 'Full Name',
  staric: '*',
  LastName: 'Last Name',
  PhoneNumber: 'Phone Number',
  Password: 'Password',
  Email: 'Email',
  ConfirmPassword: 'Confirm Password',
  alreadyHaveAccount: 'Already Have An Account?',
  haveAccountSignUp: "Don't Have Account? ",
  forgetPassword: 'Forget Password?',
  passwordRecovery: 'Password Recovery',
  backToLogin: 'Back To Login',
  continue: 'Continue',
  verification: 'Verification',
  verificationCode: 'Verification Code*',
  resend: 'Resend',
  didNt: "Didn't Receive?  ",
  youAreOnline: 'You Are Online',
  changePassword: 'Change Password',
  currentPassword: 'Current Password',
  newPassword: 'New Password',
  confirmPassword: 'Confirm Password',
  update: 'Update',
  ratingsReviews: 'Ratings & Reviews',
  contactUs: 'Contact Us',
  message: 'Message',
  send: 'Send',
  enterMessage: 'Enter Message',
  profile: 'Profile',
  editProfile: 'Edit Profile',
  edit: 'Edit',
  changePassword: 'Change Password',
  myVehicle: 'My Vehicle',
  vehicleType: 'Vehicle Type',
  editDetails: 'Edit Details',
  deleteVehicle: 'Delete Vehicle',
  yes: 'Yes',
  no: 'No',
  notifications: 'Notifications',
  viewMore: 'View More',
  areYouDeleteVehicle:
    'Are you sure you want to delete\n your vehicle details?',
  areYouLogout: 'Are you sure you want to logout?',
  save: 'Save',
  editVehicle: 'Edit Vehicle',
  registerVehicle: 'Register Vehicle',
  myEarnings: 'My Earnings',
  details: 'Details',
  vehicleType: 'Vehicle Type',
  licensePlateImage: 'License Plate Image',
  select: 'Select',
  carVehicleImage: 'Car Vehicle Image',
  brandName: 'Brand Name',
  enter: 'Enter',
  vehicleName: 'Vehicle Name',
  vehicleColor: 'Vehicle Color',
  licensePlateNumber: 'License Plate Number',
  addImage: 'Add Image',
};
